### ISSUE TITLE
Invite to a group

### ISSUE THREAD

**Issue by evanp** [swicg/groups#4]
"As an ActivityPub user, I want to invite someone to a group, so they know of a good group to join."

**Comment by mayel** [comment]
Suggested approach:

1. Support inviting someone to a group (eg. alice inviting bob):
   ```json
   {
     "type": ["Invite", "Note"],
     "actor": "https://example.org/users/alice",
     "object": "https://example.org/groups/1",
     "target": "https://example.org/users/bob",
     "to": "https://example.org/users/bob",
     "cc": "https://example.org/groups/1",
     "content": "I'd like to invite you to join [our group](https://example.org/groups/1)"
   }
   ```

2. Group verifies inviter has permission do so (group was in `cc` to be notified if inviter is on a remote instance)

3. If valid, group adds invitee to members (or an internal list of pending members) and sends `Accept{Invite}` 

4. Invitee can then a `Follow` and/or `Join` without requiring approval 

Questions: 
- Is the `target` necessary?
- Does `["Invite", "Note"]` as type make sense? Is it likely to be supported by implementations (eg. showing it as a private message if there's no specific support for invites)?

**Comment by trwnh** [comment]
> Is the target necessary?

if using AS2-Vocab's definition of as:Invite, then yes?

related issue:

- https://github.com/w3c/activitystreams/issues/619

> Does ["Invite", "Note"] as type make sense? Is it likely to be supported by implementations (eg. showing it as a private message if there's no specific support for invites)?

maybe? i'm inclined to say "weak no" from a theoretical perspective but only because as:Note is a bit weird. practically speaking mastodon might actually accept it if you use as:attributedTo explicitly instead of having it be inferred from as:actor being rdfs:subPropertyOf as:attributedTo. (mastodon doesn't do any inference.) but other softwares can trip up over this.

if we were using an additional spec like SIOC then you could say something is an as:Invite and a sioc:Post, and you could argue that mastodon is using as:Note with similar or equivalent semantics to sioc:Post...

this is something that i think must be handled at the consuming side, not the publishing side.

---

i would tentatively say something like

```yaml
actor: <alice>
type: ex:InviteToGroup
object: <bob>
target: <group>
summary: "alice invited bob to group"
content: "everyone welcome bob! (if bob accepts)"
audience: <group/members>, <bob>, <alice>
```

per related issue https://github.com/w3c/activitystreams/issues/619 we had an alternative proposal

```yaml
actor: <alice>
type: Offer
object:
  type: ex:Invitation
target: <bob>
```

i guess there's another alternative

```yaml
actor: <alice>
type: Offer
object:
  actor: <bob>
  type: Join
  object: <group>
target: <bob>
```

---

no matter what the invite format is, then bob can refer to this in the Join activity using as:instrument? the group can check the invite is valid (and consume it, etc so it counts as "used")

```
actor: <bob>
type: Join
object: <group>
instrument: <invite or offer or whatever>
to: <group>
audience: <group/members>
```
